import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { Panel } from "@/components/panels";
import { Sparkles } from "lucide-react";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid, Legend } from "recharts";

export const Route = createFileRoute("/predictive")({
  head: () => ({ meta: [{ title: "Predictive Analytics — PRAHARI" }, { name: "description", content: "AI/ML based forecasting and predictions." }] }),
  component: Predictive,
});

const data = Array.from({ length: 24 }, (_, i) => ({
  t: `${String(i).padStart(2,"0")}h`,
  high: 40 + Math.round(Math.sin(i/3)*20 + 15),
  med: 30 + Math.round(Math.cos(i/4)*15 + 10),
  low: 20 + Math.round(Math.sin(i/5)*10 + 5),
}));

function Predictive() {
  return (
    <AppShell title="Predictive Analytics Center" subtitle="AI/ML Based Forecasting & Predictions">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <ForecastCard title="Accident Risk Forecast" value="12" delta="+3 new" tone="critical" desc="High Risk Sections" />
        <ForecastCard title="Crew Fatigue Forecast" value="18" delta="+5 new" tone="warning" desc="High Risk Crews" />
        <ForecastCard title="Track Failure Forecast" value="9" delta="+2 new" tone="warning" desc="High Risk Sections" />
      </div>

      <Panel title="Risk Forecast" subtitle="Next 24 hours" className="mt-4">
        <div className="h-72">
          <ResponsiveContainer>
            <AreaChart data={data}>
              <defs>
                <linearGradient id="h" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#FF4D4F" stopOpacity={0.4} /><stop offset="100%" stopColor="#FF4D4F" stopOpacity={0} /></linearGradient>
                <linearGradient id="m" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#FFB020" stopOpacity={0.4} /><stop offset="100%" stopColor="#FFB020" stopOpacity={0} /></linearGradient>
                <linearGradient id="l" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22C55E" stopOpacity={0.4} /><stop offset="100%" stopColor="#22C55E" stopOpacity={0} /></linearGradient>
              </defs>
              <CartesianGrid stroke="rgba(255,255,255,0.04)" />
              <XAxis dataKey="t" stroke="#475569" fontSize={10} />
              <YAxis stroke="#475569" fontSize={10} />
              <Tooltip contentStyle={{ background: "#0D1525", border: "1px solid rgba(255,255,255,0.08)" }} />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Area type="monotone" dataKey="high" stroke="#FF4D4F" fill="url(#h)" name="High Risk" />
              <Area type="monotone" dataKey="med" stroke="#FFB020" fill="url(#m)" name="Medium Risk" />
              <Area type="monotone" dataKey="low" stroke="#22C55E" fill="url(#l)" name="Low Risk" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </Panel>

      <Panel title="AI Insights" subtitle="Generated by PRAHARI ML Pipeline" className="mt-4"
        action={<span className="inline-flex items-center gap-1 text-[11px] text-purple"><Sparkles className="h-3.5 w-3.5" /> Model: rail-fcst-v7</span>}>
        <ul className="space-y-2.5 text-[12px]">
          {[
            "Increase in fatigue risk between 02:00 — 06:00 AM (night shift density)",
            "Track failure probability high in KM 140 — KM 145 corridor",
            "Signal delay likely due to weather conditions in Eastern coast",
            "Predicted 4-7 incidents in next 24h across Central Zone",
            "Bridge Br-082 trending toward maintenance threshold in 48h",
          ].map((t, i) => (
            <li key={i} className="flex items-start gap-2 rounded-md border border-purple/20 bg-purple/5 px-3 py-2">
              <Sparkles className="h-3.5 w-3.5 text-purple shrink-0 mt-0.5" />
              <span>{t}</span>
            </li>
          ))}
        </ul>
      </Panel>
    </AppShell>
  );
}

function ForecastCard({ title, value, delta, tone, desc }: { title: string; value: string; delta: string; tone: "critical"|"warning"|"info"; desc: string }) {
  const c = tone==="critical"?"text-critical":tone==="warning"?"text-warning":"text-info";
  return (
    <Panel title={title}>
      <div className="flex items-end justify-between">
        <div>
          <div className={`text-mono text-4xl font-bold ${c}`}>{value}</div>
          <div className="text-[11px] text-muted-foreground mt-1">{desc}</div>
        </div>
        <span className={`text-[11px] ${c}`}>({delta})</span>
      </div>
      <div className="mt-3 h-12">
        <ResponsiveContainer>
          <AreaChart data={data.slice(0, 10)}>
            <defs><linearGradient id={`mini-${tone}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={tone==="critical"?"#FF4D4F":tone==="warning"?"#FFB020":"#3B82F6"} stopOpacity={0.5} /><stop offset="100%" stopColor={tone==="critical"?"#FF4D4F":tone==="warning"?"#FFB020":"#3B82F6"} stopOpacity={0} /></linearGradient></defs>
            <Area type="monotone" dataKey="high" stroke={tone==="critical"?"#FF4D4F":tone==="warning"?"#FFB020":"#3B82F6"} fill={`url(#mini-${tone})`} strokeWidth={1.5} />
          </AreaChart>
        </ResponsiveContainer>
      </div>
    </Panel>
  );
}
