/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictiveRouteImport } from './routes/predictive'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as CyberRouteImport } from './routes/cyber'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CcrsRouteImport } from './routes/ccrs'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveRoute = PredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberRoute = CyberRouteImport.update({
  id: '/cyber',
  path: '/cyber',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CcrsRoute = CcrsRouteImport.update({
  id: '/ccrs',
  path: '/ccrs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ccrs': typeof CcrsRoute
  '/copilot': typeof CopilotRoute
  '/crew': typeof CrewRoute
  '/cyber': typeof CyberRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network-map': typeof NetworkMapRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/seed': typeof SeedRoute
  '/settings': typeof SettingsRoute
  '/signal': typeof SignalRoute
  '/splash': typeof SplashRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ccrs': typeof CcrsRoute
  '/copilot': typeof CopilotRoute
  '/crew': typeof CrewRoute
  '/cyber': typeof CyberRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network-map': typeof NetworkMapRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/seed': typeof SeedRoute
  '/settings': typeof SettingsRoute
  '/signal': typeof SignalRoute
  '/splash': typeof SplashRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ccrs': typeof CcrsRoute
  '/copilot': typeof CopilotRoute
  '/crew': typeof CrewRoute
  '/cyber': typeof CyberRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/network-map': typeof NetworkMapRoute
  '/predictive': typeof PredictiveRoute
  '/reports': typeof ReportsRoute
  '/seed': typeof SeedRoute
  '/settings': typeof SettingsRoute
  '/signal': typeof SignalRoute
  '/splash': typeof SplashRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ccrs'
    | '/copilot'
    | '/crew'
    | '/cyber'
    | '/incidents'
    | '/infrastructure'
    | '/login'
    | '/maintenance'
    | '/network-map'
    | '/predictive'
    | '/reports'
    | '/seed'
    | '/settings'
    | '/signal'
    | '/splash'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ccrs'
    | '/copilot'
    | '/crew'
    | '/cyber'
    | '/incidents'
    | '/infrastructure'
    | '/login'
    | '/maintenance'
    | '/network-map'
    | '/predictive'
    | '/reports'
    | '/seed'
    | '/settings'
    | '/signal'
    | '/splash'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ccrs'
    | '/copilot'
    | '/crew'
    | '/cyber'
    | '/incidents'
    | '/infrastructure'
    | '/login'
    | '/maintenance'
    | '/network-map'
    | '/predictive'
    | '/reports'
    | '/seed'
    | '/settings'
    | '/signal'
    | '/splash'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CcrsRoute: typeof CcrsRoute
  CopilotRoute: typeof CopilotRoute
  CrewRoute: typeof CrewRoute
  CyberRoute: typeof CyberRoute
  IncidentsRoute: typeof IncidentsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NetworkMapRoute: typeof NetworkMapRoute
  PredictiveRoute: typeof PredictiveRoute
  ReportsRoute: typeof ReportsRoute
  SeedRoute: typeof SeedRoute
  SettingsRoute: typeof SettingsRoute
  SignalRoute: typeof SignalRoute
  SplashRoute: typeof SplashRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive': {
      id: '/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof PredictiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber': {
      id: '/cyber'
      path: '/cyber'
      fullPath: '/cyber'
      preLoaderRoute: typeof CyberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ccrs': {
      id: '/ccrs'
      path: '/ccrs'
      fullPath: '/ccrs'
      preLoaderRoute: typeof CcrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CcrsRoute: CcrsRoute,
  CopilotRoute: CopilotRoute,
  CrewRoute: CrewRoute,
  CyberRoute: CyberRoute,
  IncidentsRoute: IncidentsRoute,
  InfrastructureRoute: InfrastructureRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NetworkMapRoute: NetworkMapRoute,
  PredictiveRoute: PredictiveRoute,
  ReportsRoute: ReportsRoute,
  SeedRoute: SeedRoute,
  SettingsRoute: SettingsRoute,
  SignalRoute: SignalRoute,
  SplashRoute: SplashRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
